language: go

go:
  - "1.14.x"
env:
  global:
    - GO_REPO_FULLNAME="github.com/jianzhiyao/gclient" TEST_TARGET=http://127.0.0.1:8080/
  matrix:
    - BENCHMARK_TARGET=http://127.0.0.1:8080/benchmark BENCHMARK_LIMIT=50
    - BENCHMARK_TARGET=http://127.0.0.1:8080/benchmark BENCHMARK_LIMIT=100
    - BENCHMARK_TARGET=https://www.google.com/ BENCHMARK_LIMIT=50
    - BENCHMARK_TARGET=https:/www.google.com/ BENCHMARK_LIMIT=100
    - BENCHMARK_TARGET=https://www.bing.com/ BENCHMARK_LIMIT=50
    - BENCHMARK_TARGET=https:/www.bing.com/ BENCHMARK_LIMIT=100
before_install:
  # link the local repo with ${GOPATH}/src/<namespace>/<repo>
  - GO_REPO_NAMESPACE=${GO_REPO_FULLNAME%/*}
  # relies on GOPATH to contain only one directory...
  - mkdir -p ${GOPATH}/src/${GO_REPO_NAMESPACE}
  - ln -sv ${TRAVIS_BUILD_DIR} ${GOPATH}/src/${GO_REPO_FULLNAME}
  - cd ${GOPATH}/src/${GO_REPO_FULLNAME}
install:
  - go version
  # run in background
  - go run scripts/server.go >/dev/null 2>&1 &
before_script:
  - sleep 10
  - go version
after_script:
  - go version
after_success:
  - bash <(curl -s https://codecov.io/bash)
script:
  - go test -coverprofile=coverage.txt -covermode=atomic -bench=. -benchmem ./...
