language: go

go:
  - "1.14.x"
  - "1.15.x"
services:
  - nginx
env:
  global:
    - GO_REPO_FULLNAME="github.com/jianzhiyao/gclient"
  matrix:
    - TEST_TARGET=https://google.com
    - TEST_TARGET=https://bing.com
before_install:
  # link the local repo with ${GOPATH}/src/<namespace>/<repo>
  - GO_REPO_NAMESPACE=${GO_REPO_FULLNAME%/*}
  # relies on GOPATH to contain only one directory...
  - mkdir -p ${GOPATH}/src/${GO_REPO_NAMESPACE}
  - ln -sv ${TRAVIS_BUILD_DIR} ${GOPATH}/src/${GO_REPO_FULLNAME}
  - cd ${GOPATH}/src/${GO_REPO_FULLNAME}
install:
  - go version
before_script:
  - go version
after_script:
  - go version
after_success:
  - bash <(curl -s https://codecov.io/bash)
script:
  - go test -coverprofile=coverage.txt -covermode=atomic -bench=. -benchmem ./...
